package com.visfresh.drools
 
import com.visfresh.rules.AssignShipmentRule;
import com.visfresh.rules.OpenJtsRule;
import com.visfresh.rules.RuleContext;
import com.visfresh.rules.HighTemperatureAlertRule;
import com.visfresh.rules.CriticalHighTemperatureAlertRule;
import com.visfresh.rules.LowTemperatureAlertRule;
import com.visfresh.rules.CriticalLowTemperatureAlertRule;
import com.visfresh.rules.EnterBrightEnvironmentAlertRule;
import com.visfresh.rules.EnterDarkEnvironmentAlertRule;
import com.visfresh.rules.BatteryLowAlertRule;
import com.visfresh.rules.ArrivalRule;
import com.visfresh.rules.AutoStartShipmentRule;
import com.visfresh.rules.MovementStartAlertRule;
import com.visfresh.rules.MovementStopAlertRule;
import com.visfresh.rules.AbstractRuleEngine;

global AbstractRuleEngine engine;

rule "AssignShipment"
	salience 100
    when
        req : RuleContext(engine.getRule(AssignShipmentRule.NAME).accept(this));
    then
    	if(engine.getRule(AssignShipmentRule.NAME).handle(req)) {
       		update(req);
        }
end

rule "AutoStartShipment"
	salience 50
    when
        req : RuleContext(engine.getRule(AutoStartShipmentRule.NAME).accept(this));
    then
    	if(engine.getRule(AutoStartShipmentRule.NAME).handle(req)) {
       		update(req);
        }
end

rule "OpenGts"
    when
        req : RuleContext(engine.getRule(OpenJtsRule.NAME).accept(this));
    then
    	if(engine.getRule(OpenJtsRule.NAME).handle(req)) {
       		update(req);
        }
end

rule "HighTemperatureAlert"
    when
        req : RuleContext(engine.getRule(HighTemperatureAlertRule.NAME).accept(this));
    then
    	if(engine.getRule(HighTemperatureAlertRule.NAME).handle(req)) {
       		update(req);
        }
end

rule "CriticalHighTemperatureAlert"
    when
        req : RuleContext(engine.getRule(CriticalHighTemperatureAlertRule.NAME).accept(this));
    then
    	if(engine.getRule(CriticalHighTemperatureAlertRule.NAME).handle(req)) {
       		update(req);
        }
end

rule "LowTemperatureAlert"
    when
        req : RuleContext(engine.getRule(LowTemperatureAlertRule.NAME).accept(this));
    then
    	if(engine.getRule(LowTemperatureAlertRule.NAME).handle(req)) {
       		update(req);
        }
end

rule "CriticalLowTemperatureAlert"
    when
        req : RuleContext(engine.getRule(CriticalLowTemperatureAlertRule.NAME).accept(this));
    then
    	if(engine.getRule(CriticalLowTemperatureAlertRule.NAME).handle(req)) {
       		update(req);
        }
end

rule "EnterBrightEnvironmentAlert"
    when
        req : RuleContext(engine.getRule(EnterBrightEnvironmentAlertRule.NAME).accept(this));
    then
    	if(engine.getRule(EnterBrightEnvironmentAlertRule.NAME).handle(req)) {
       		update(req);
        }
end

rule "EnterDarkEnvironmentAlert"
    when
        req : RuleContext(engine.getRule(EnterDarkEnvironmentAlertRule.NAME).accept(this));
    then
    	if(engine.getRule(EnterDarkEnvironmentAlertRule.NAME).handle(req)) {
       		update(req);
        }
end

rule "BatteryLowAlert"
    when
        req : RuleContext(engine.getRule(BatteryLowAlertRule.NAME).accept(this));
    then
    	if(engine.getRule(BatteryLowAlertRule.NAME).handle(req)) {
       		update(req);
        }
end

rule "Arrival"
    when
        req : RuleContext(engine.getRule(ArrivalRule.NAME).accept(this));
    then
    	if(engine.getRule(ArrivalRule.NAME).handle(req)) {
       		update(req);
        }
end

rule "MovementStartAlert"
    when
        req : RuleContext(engine.getRule(MovementStartAlertRule.NAME).accept(this));
    then
    	if(engine.getRule(MovementStartAlertRule.NAME).handle(req)) {
       		update(req);
        }
end

rule "MovementStopAlert"
    when
        req : RuleContext(engine.getRule(MovementStopAlertRule.NAME).accept(this));
    then
    	if(engine.getRule(MovementStopAlertRule.NAME).handle(req)) {
       		update(req);
        }
end
